ERROR 2018-09-25 04:39:55,745 ldapop 5072 140735799808960 ldapop.py.ldap_get:91 {'desc': 'Invalid credentials'}
